management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
#  metrics:
#    web:
#      server:
#        request:
#          autotime:
#            enabled: true
#      client:
#        request:
#          autotime:
#            enabled: true
#    export:
#      prometheus:
#        enabled: true
#    distribution:
#      percentiles-histogram:
#        "[http.server.requests]": true